autoload -Uz compinit && compinit
# . `brew --prefix`/etc/profile.d/z.sh
#
source ~/antigen.zsh
# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Load the theme
# antigen theme https://github.com/denysdovhan/spaceship-zsh-theme spaceship

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
# antigen bundle heroku
# antigen bundle pip
# antigen bundle lein
# antigen bundle command-not-found
# antigen bundle autojump
# antigen bundle common-aliases
# antigen bundle compleat
antigen bundle git-extras
antigen bundle git-flow
# antigen bundle npm
antigen bundle web-search
# antigen bundle zsh-users/zsh-history-substring-search ./zsh-history-substring-search.zsh
antigen bundle autosuggestions
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=8'
antigen bundle zsh-users/zsh-autosuggestions

# jump to recently used directories by typing the first few letters in the
# directory name
antigen bundle z
# fuzzy search of most recently used directories
# antigen bundle b4b4r07/enhancd

# pure theme
# antigen bundle mafredri/zsh-async
# antigen bundle sindresorhus/pure

# .zshrc
# fpath+=($HOME/.zsh/pure)
autoload -U promptinit; promptinit
prompt pure

antigen bundle zsh-users/zsh-syntax-highlighting
# Tell Antigen that you're done.
antigen apply



# Setup zsh-autosuggestions
# source "$HOME/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh"

# Load custom aliases
[[ -s "$HOME/.bash_aliases" ]] && source "$HOME/.bash_aliases"


# VIM STUFF
bindkey -v
# bindkey '^O' 'cd -'


 function go_previous_directory() {
	 cd -
   # zle reset-prompt
 }

 zle -N go_previous_directory
 # bindkey '^o' go_previous_directory
 bindkey '^o' push_line

#kill the lag (switching modes)
export KEYTIMEOUT=1


# tmux working dynamic cursor function
# ZLE hooks for prompt's Vim mode status
function zle-line-init zle-keymap-select {
	# Change the cursor style depending on keymap mode.
	if [[ "$SSH_CONNECTION" == '' ]] {
		case $KEYMAP {
			vicmd)
				printf '\e[2 q' # Box.
				;;

			viopp)
				printf '\e[6 q' # Vertical bar.
				;;

			viins|main)
				printf '\e[6 q' # Vertical bar.
				;;
		}
	}

	# Redraw if necessary.
	zle reset-prompt
	zle -R
}
zle -N zle-line-init
zle -N zle-line-finish
zle -N zle-keymap-select

# mappings
# alias nvim '~/.nvim-macos/bin/nvim'
alias hi="echo 'hi'"
alias v=nvim
alias lg=lazygit
bindkey '^E' autosuggest-accept
# bindkey -s ^F 'nvim "$(fzf --preview \"cat {}\")"\015'

# fuzzy find a file
alias f="fzf --bind 'enter:become(nvim {})' --preview 'bat --style=numbers --color=always {}'"

# fuzzy find a directory
alias c='cd $(find * -type d | fzf)'

cmd="${FZF_CTRL_T_COMMAND:-"command find -L . -mindepth 1 \\( -path '*/\\.*' -o -fstype 'sysfs' -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'proc' \\) -prune \
-o -type f -print \
-o -type d -print \
-o -type l -print 2> /dev/null | cut -b3-"}"

source ~/.aliases.zsh

eval $(thefuck --alias)

export PATH=$HOME/omnetpp-5.6.1/bin:$HOME/omnetpp-5.6.1/tools/macosx/bin:$PATH
export QT_PLUGIN_PATH=$HOME/omnetpp-5.6.1/tools/macosx/plugins

export TMPDIR=~/gctmp

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/jeremysmith/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/jeremysmith/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/jeremysmith/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/jeremysmith/google-cloud-sdk/completion.zsh.inc'; fi

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/jeremysmith/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/jeremysmith/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/jeremysmith/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/jeremysmith/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# location of fzf-file-widget:
# source "/usr/local/opt/fzf/shell/key-bindings.zsh"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
